#!/bin/bash

if [ "$1" = "test" ]; then
  outfile='./testout.txt'
  path='./test/'
else
  outfile='./out.txt'
  path='./texts/'
fi
while read input
do
    if [[ -z $input ]]
    then
      echo "Readin done"
    else
      file="$path$input"
      echo $file
      cat $file | tr -d '\n\r' >> $outfile
      echo "" >> $outfile
    fi
done
